# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.network 'private_network', ip: "192.168.0.205",  virtualbox__intnet: true
  config.vm.box = "hashicorp/bionic64"
  config.vm.box_version = "1.0.282"
  config.vm.network "forwarded_port", guest: 10000, host: 10000
  config.vm.network "forwarded_port", guest: 8090, host: 8090
  config.vm.network "forwarded_port", guest: 8091, host: 8091
  config.vm.provision :shell, :privileged => false, :path => "scripts/install-bcc.sh"
  config.vm.provider "virtualbox" do |v|
    v.memory = 4096
end
end